name: ci
channels:
  - bioconda
  - conda-forge
dependencies:
  - aiohttp==3.11.*
  - biopython==1.85
  - pytest
  - pytest-asyncio
  - python-build
  - conda-build
  - twine==6.0.1
  - setuptools_scm
  - pytest-cov
  - grayskull
  - curl